apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-app
  namespace: default
spec:
  project: task-app
  source:
    repoURL: https://github.com/rahul-tarka/learn-app-repo
    targetRevision: HEAD
    path: helm/task-app
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
